GeniusBase.Web/Controllers/ArticleController.cs
using GeniusBase.Dal;
using GeniusBase.Dal.Repository;
using GeniusBase.Web.Business.Articles;
using GeniusBase.Web.Models.New;
using NLog;
using NLog.Fluent;
using System;
using System.Linq;
using System.Web.Mvc;

namespace GeniusBase.Web.Controllers
{
    public class ArticleController : Controller
    {
        public IArticleRepository ArticleRepository { get; set; }
        public IArticleFactory ArticleFactory { get; set; }
        protected Logger Log = LogManager.GetCurrentClassLogger();

        public ActionResult Show(string id)
        {
            using (var db = new GeniusBaseContext())
            {
                var article = db.PublishedArticles().FirstOrDefault(a => a.SefName == id);

                if (article == null)
                {
                    return View(new ArticleViewModel());
                }

                article.Views++;
                db.SaveChanges();

                var articleViewModel = new ArticleViewModel
                {
                    ArticleId = article.Id,
                    Title = article.Title,
                    Content = article.Content,
                    CategorySef = article.Category.SefName,
                    CategoryName = article.Category.Name,
                    Tags = article.ArticleTags.Select(a => a.Tag.Name).ToList()
                };

                return View(articleViewModel);                
            }
        }


        public ActionResult Edit(int id)
        {
            try
            {
                return View("Create", ArticleFactory.CreateArticleViewModel(ArticleRepository.Get(id)));
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

GeniusBase.Web/Controllers/BackupController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Core.EntityClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using GeniusBase.Backup;
using GeniusBase.Backup.Classes;
using GeniusBase.Backup.Interface;
using GeniusBase.Web.Models;
using Resources;

namespace GeniusBase.Web.Controllers
{
    public class BackupController : GeniusBaseAdminController
    {        

        public ActionResult Index()
        {
            string BackupDirectory = "";
            if (!string.IsNullOrEmpty(Settings.BackupPath) && Settings.BackupPath.StartsWith("~"))
            {
                BackupDirectory = Server.MapPath(Settings.BackupPath);
            }
            else
            {
                BackupDirectory = Settings.BackupPath;
            }
            List<BackupListViewModel> model = new List<BackupListViewModel>();            
            int i = 0;
            if (!string.IsNullOrEmpty(BackupDirectory))
            {
                foreach (var filePath in Directory.GetFiles(BackupDirectory, "*.bak"))
                {
                    FileInfo fo = new FileInfo(filePath);
                    model.Add(new BackupListViewModel()
                    {
                        Id = i,
                        FileName = Path.GetFileName(filePath),
                        FileDate = fo.CreationTime
                    });
                    i++;
                }
            }
            return View(model.OrderByDescending( f => f.FileDate));
        }


        [HttpPost]
        public JsonResult Restore(string file)
        {
            try
            {
                JsonOperationResponse result = new JsonOperationResponse();
                try
                {
                    string backupFile = "";
                    if (Settings.BackupPath.StartsWith("~"))
                    {
                        backupFile = Server.MapPath(Settings.BackupPath + file);
                    }
                    else
                    {
                        backupFile = Settings.BackupPath + file;
                    }
                    if (System.IO.File.Exists(backupFile))
                    {
                        string connectionString = ConfigurationManager.ConnectionStrings["GeniusBaseEntities"].ConnectionString;
                        EntityConnectionStringBuilder entityConnectionString = new EntityConnectionStringBuilder(connectionString);
                        System.Data.SqlClient.SqlConnectionStringBuilder builder = new System.Data.SqlClient.SqlConnectionStringBuilder(entityConnectionString.ProviderConnectionString);

                        IVaultBackup backup = new VaultMsSqlBackup();
                        backup.Connect(entityConnectionString.ProviderConnectionString);
                        result.Successful = backup.Restore(builder.InitialCatalog, backupFile);
                        if (result.Successful)
                            result.ErrorMessage = UIResources.BackupRestoreSuccessfull;
                    }
                    else
                    {
                        throw new FileNotFoundException(file);
                    }
                }
                catch (Exception ex)
                {
                    Log.Error(ex);
                    result.ErrorMessage = ex.Message;
                }
                return Json(result, JsonRequestBehavior.DenyGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                throw;
            }
        }

        [HttpPost]
        public JsonResult BackupNow()
        {
            try
            {
                JsonOperationResponse result = new JsonOperationResponse();
                if (string.IsNullOrEmpty(Settings.BackupPath))
                {
                    result.Successful = false;
                    result.ErrorMessage = ErrorMessages.BackupPathIsNotSet;
                }
                else
                {
                    string connectionString = ConfigurationManager.ConnectionStrings["GeniusBaseContext"].ConnectionString;
                    System.Data.SqlClient.SqlConnectionStringBuilder builder = new System.Data.SqlClient.SqlConnectionStringBuilder(connectionString);
                    IVaultBackup backup = new VaultMsSqlBackup();
                    backup.Connect(connectionString);
                    string backupFile = string.Format("{0:yyyyMddhhmm}.bak", DateTime.Now);
                    if (!string.IsNullOrEmpty(Settings.BackupPath) && Settings.BackupPath.StartsWith("~"))
                    {
                        backupFile = Server.MapPath(Settings.BackupPath + backupFile);
                    }
                    else
                    {
                        backupFile = Settings.BackupPath + backupFile;
                    }
                    bool b = backup.Backup(builder.InitialCatalog, backupFile);
                    if (b)
                    {
                        if (!String.IsNullOrEmpty(backupFile))
                        {
                            result.Data = backupFile;
                            result.Successful = true;
                        }
                    }
                }
                
                return Json(result, JsonRequestBehavior.DenyGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                throw;
            }
        }

    }
}

GeniusBase.Web/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GeniusBase.Web.Controllers
{
    public class SearchController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

GeniusBase.Web/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GeniusBase.Dal;
using GeniusBase.Dal.Entities;
using GeniusBase.Dal.Repository;
using NLog;
using MvcPaging;
using GeniusBase.Web.Models;

using Resources;
using GeniusBase.Web.Helpers;

namespace GeniusBase.Web.Controllers
{
    [Authorize(Roles="Admin,Manager")]
    public class TagController : GeniusBaseAdminController
    {
        
        private int PageSize = 45;

        public ITagRepository TagRepository { get; set; }

        [HttpPost]
        public JsonResult Edit(string name, string pk, string value)
        {
            JsonOperationResponse result = new JsonOperationResponse();
            try
            {
                using (var db = new GeniusBaseContext())
                {
                    long tagId = Convert.ToInt64(pk);
                    Tag tag = db.Tags.First(t => t.Id == tagId);
                    if (tag != null)
                    {
                        tag.Author = HelperFunctions.UserAsKbUser(User).Id;
                        tag.Name = value;
                        db.SaveChanges();
                        result.Successful = true;
                        return Json(result);
                    }
                }
                return null;
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                result.Successful = false;
                result.ErrorMessage = ex.Message;
                return Json(result);
            }
        }

        [HttpPost]
        public JsonResult Remove(int id = -1)
        {
            JsonOperationResponse result = new JsonOperationResponse();
            result.Successful = false;
            try
            {
                using (var db = new GeniusBaseContext())
                {
                    
                    Tag tag = db.Tags.First(t => t.Id == id);
                    if (tag != null)
                    {
                        tag.Author = HelperFunctions.UserAsKbUser(User).Id;
                        db.Tags.Remove(tag);
                        TagRepository.RemoveTagFromArticles(id);
                        db.SaveChanges();
                        result.Successful = true;
                        result.ErrorMessage = UIResources.TagListRemoveSuccessful;
                    }
                    else
                    {
                        result.ErrorMessage = ErrorMessages.TagNotFound;
                    }
                }
                return Json(result);
            }
            catch (Exception ex)
            {
                Log.Error(ex);                
                result.ErrorMessage = ex.Message;
                return Json(result);
            }
        }

        public ActionResult List(int page = 1)
        {
            try
            {
                if (page < 1)
                    page = 1;
                using (var db = new GeniusBaseContext())
                {
                    IList<Tag> Tags = db.Tags.OrderBy(t => t.Name).ToPagedList(page, PageSize);
                    return View(Tags);
                }                
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("Index", "Error");
            }
            
        }

        [Authorize(Roles="Admin,Manager,Editor")]
        public JsonResult Suggest(string term)
        {
            JsonOperationResponse result = new JsonOperationResponse();
            try
            {                
                using (var db = new GeniusBaseContext())
                {
                    var suggestions = db.Tags.Where(t => t.Name.Contains(term)).Select(t => t.Name).Take(20).ToList<string>();
                    result.Successful = true;
                    result.Data = suggestions.ToArray();
                    return Json(result);
                }                                
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                result.Successful = false;
                result.ErrorMessage = ex.Message;
                return Json(result);
            }
        }
    }
}

GeniusBase.Web/Views/Shared/GoogleFonts.cshtml
@if( Request.IsSecureConnection )
{
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800" />
}
else
{
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800" />
}

GeniusBase.Web/Views/Shared/_Admin_Layout.cshtml
@using GeniusBase.Dal.Entities
@{
    KbUser CurrentUserInfo = HelperFunctions.UserAsKbUser(Context.User);
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - GeniusBase</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width" />
    
    @*if (Request.Browser.Browser.Contains("InternetExplorer"))
     {
        <meta http-equiv="x-ua-compatible" content="IE=11" />
     } *@
        
    @{ Html.RenderPartial("GoogleFonts"); }     
    @Styles.Render("~/admin/css")       
</head>
 <body class="skin-blue">
     
    <header class="header">
        <a href='@Url.Action("Index", "Dashboard")' class="logo">        
            <img src='@Url.Content("~/Assets/img/vault.png")' width="48" /> GeniusBase
        </a>
        <nav class="navbar navbar-static-top" role="navigation">
            <div class="navbar-right">
                <ul class="nav navbar-nav">

                    <li class="dropdown user user-menu">
                        <a href='#' class="dropdown-toggle" data-toggle="dropdown">
                            <img src="@CurrentUserInfo.GravatarImageUrl" width="16" />                            
                            <span>@CurrentUserInfo.Name @CurrentUserInfo.LastName<i class="caret"></i></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header bg-light-blue">
                                <img src="@CurrentUserInfo.GravatarImageUrl" class="img-circle"/>
                                <p>@CurrentUserInfo.Name @CurrentUserInfo.LastName</p>
                            </li>                           
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="@Url.Action("MyProfile", "Account")" class="btn btn-default btn-flat">Profile</a>
                                </div>
                                <div class="pull-right">
                                    <a href='@Url.Action("Logout", "Account")' class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>

                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="wrapper row-offcanvas row-offcanvas-left">
        <aside class="left-side sidebar-offcanvas">
            <section class="sidebar"> 
                <ul class="sidebar-menu">
                    @if (HelperFunctions.IsAdmin(Context.User) || HelperFunctions.IsManager(Context.User))
                    {
                    <li>
                        <div>
                            <a href='@Url.Action("Index", "Settings")'>
                                <i class="fa fa-gear"></i> <span>@UIResources.LeftSideBarSettings</span>
                            </a>
                        </div>
                    </li>
                    }
                    <li>
                        <div>
                            <a href='@Url.Action("Create", "Article")'>
                                <i class="fa fa-pencil"></i> <span>@UIResources.LeftSidebarCreateArticle</span>
                            </a>
                        </div>
                    </li>
                    @if (HelperFunctions.IsAdmin(Context.User) || HelperFunctions.IsManager(Context.User))
                    {
                    <li>     
                        <div>
                            <a href='@Url.Action("Create", "Category")'>
                                <i class="fa fa-plus"></i> <span>@UIResources.LeftSidebarCreateCategory</span>
                            </a>
                        </div>                       
                    </li>
                    }
                    <li class="treeview active">                                                
                        <div>
                            <a href="#" class="trigger-item">
                                <i class="fa fa-folder"></i>
                                <span>@UIResources.LeftSidebarCategoryListTitle</span>                                                                                                                                     
                            </a>                                
                       </div>      
                        
                        @HelperFunctions.CreateCategoryMenu()
                        
                    </li>
                    @if (HelperFunctions.IsAdmin(Context.User))
                    {
                    <li>
                        <div>
                            <a href='@Url.Action("Users", "Account")'>
                                <i class="fa fa-user"></i>
                                @UIResources.LeftSidebarUserMenuTitle
                            </a>
                        </div>
                    </li>
                    }
                    @if (HelperFunctions.IsAdmin(Context.User) || HelperFunctions.IsManager(Context.User))
                    {
                    <li>
                        <div>
                            <a href='@Url.Action("List", "Tag")'>
                                <i class="fa fa-tag"></i>
                                @UIResources.LeftSideBarTagsTitle
                            </a>
                        </div>
                    </li>
                    }
                    @if (HelperFunctions.IsAdmin(Context.User))
                    {
                    <li>
                        <div>
                            <a href='@Url.Action("Index", "Activity")'>
                                <i class="fa fa-desktop"></i>
                                @UIResources.LeftSideBarActivitiesTitle
                            </a>
                        </div>
                    </li>
                        <li>
                            <div>
                                <a href="@Url.Action("Index","Backup")">
                                    <i class="fa fa-briefcase"></i>
                                    @UIResources.LeftSideBarBackupTitle
                                </a>
                            </div>
                        </li>
                        <li>
                            <div>
                                <a href="@Url.Action("Index","Indexing")">
                                    <i class="fa fa-book"></i>
                                    @UIResources.IndexingLeftMenuTitle
                                </a>
                            </div>
                        </li>
                    }
                    
                </ul>
            </section>
        </aside>
        <aside class="right-side">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                @RenderSection("ContentHeader", required: false)                
            </section>

            <!-- Main content -->
            <section class="content">
                @if (ViewBag.ShowOperationMessage != null && ViewBag.ShowOperationMessage)
                {
                    <div class="alert alert-success alert-dismissable">
                        <i class="fa fa-check"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        @ViewBag.OperationMessage
                    </div>
                }
                 @if (ViewBag.ShowErrorMessage != null && ViewBag.ShowErrorMessage)
                 {
                    <div class="alert alert-danger alert-dismissable">
                        <i class="fa fa-check"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        @ViewBag.ErrorMessage
                    </div>
                 }
                @RenderBody()
            </section>
        </aside>
    </div>
    
    @Scripts.Render("~/admin/js")     
     <script src="~/signalr/hubs"></script>
    <script>
            $(document).ready(function () {                
                @RenderSection("Scripts", required: false)
            });
        </script>
</body>
</html>

GeniusBase.Web/Views/Shared/_Layout.cshtml
@{
    var searchTerm = "";
    if (ViewBag.SearchTerm != null)
    {
        searchTerm = ViewBag.SearchTerm;
    }
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@ViewBag.Title</title>

    @Styles.Render("~/bundles/css/lib")
    @Scripts.Render("~/bundles/js/lib")
    @RenderSection("CssHeader", required: false)
    <script type="text/javascript">
        var KB_SearchUrl = "@Url.Action("Ajax","Search")";
    </script>
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <img src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="40" height="40" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="container-fluid pt-2">
                <div class="row justify-content-md-center">
                    <div class="col-md-8">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend d-none d-md-block">
                                <button class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="search-category-selected" data-selected-category-id="0">All</button>
                                <div class="dropdown-menu" id="search-categroy">
                                    <a class="dropdown-item" data-categoryId="1">Action</a>
                                    <a class="dropdown-item" data-categoryId="2">Another action</a>
                                    <a class="dropdown-item" data-categoryId="3">Something else here</a>
                                </div>
                            </div>
                            <input type="text" class="form-control" id="search-text" placeholder="Search for articles">
                            <div class="input-group-append">
                                <a class="input-group-text" id="search-button"><i class="fas fa-search"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="~/Account/Login">Login</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

    <footer class="blockquote-footer text-center mt-5">
        Powered by Genius Base
    </footer>

    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function (e) {
            $("#search-categroy")
                .find("a")
                .click(function (e) {
                    e.preventDefault();
                    var categoryId = $(this).data('categoryid');
                    var categoryDescription = $(this).text();
                    $("#search-category-selected").html(categoryDescription);
                    $("#search-category-selected").data('selectedCategoryId', categoryId);
                });
        });

        $("#search-button").click(function () {
            search();
        });

        function search() {
            alert(
                "Category: " + $("#search-category-selected").text() +
                " \nSearch Text: " +  $("#search-text").val()
            );
        }

    </script>
</body>
</html>